# Generated by Django 4.1.7 on 2023-06-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('blood_group', models.CharField(max_length=5)),
                ('mobile_no', models.IntegerField()),
                ('address', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
    ]
