# Generated by Django 4.1.7 on 2023-12-15 13:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_detail_delete_feature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='id',
        ),
        migrations.AddField(
            model_name='detail',
            name='serial',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
