# Generated by Django 4.1.7 on 2023-12-15 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_detail_id_detail_serial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='serial',
            new_name='id',
        ),
    ]
